In [4]:
# Step 1: Import NumPy
import numpy as np

# Step 2: Create a 1D array representing years of experience
years_exp = np.array([1, 3, 5, 7, 10])
print("Years of Experience:", years_exp)

# Step 3: Create a 2D array representing sample salaries (in thousands)
salaries = np.array([[50, 60, 70], [80, 90, 100]])
print("Salary Matrix:\n", salaries)

# Step 4: Create an array of zeros and ones for placeholder analysis
zeros_array = np.zeros((2, 2)) # 2x2 zeros
ones_array = np.ones((2, 3)) # 2x3 ones
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)

Years of Experience: [ 1  3  5  7 10]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
# Step 1: Element-wise addition
exp_plus_5 = years_exp + 5 # Add 5 years to all experience values
print("Years + 5:", exp_plus_5)

# Step 2: Element-wise multiplication
exp_times_2 = years_exp * 2 # Multiply all values by 2
print("Years * 2:", exp_times_2)

# Step 3: Dot product (simulate salary projections)
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result)

Years + 5: [ 6  8 10 12 15]
Years * 2: [ 2  6 10 14 20]
Dot Product: 32


In [6]:
# Step 1: Access individual element
print("First year of experience:", years_exp[0])

# Step 2: Slice arrays
print("First two salaries:", salaries[0, :2]) # First two elements of first row

# Step 3: Access all rows for a specific column
print("Second column salaries:", salaries[:, 1])

# Step 4: Negative indexing
print("Last year of experience:", years_exp[-1])

First year of experience: 1
First two salaries: [50 60]
Second column salaries: [60 90]
Last year of experience: 10


In [7]:
# Step 1: Reshape 1D array into 2x3 matrix for batch analysis
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Experience Array:\n", reshaped_exp)

# Step 2: Flatten 2D arrays back into 1D
flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp)

# Step 3: Transpose example
print("Transposed Array:\n", reshaped_exp.T)

Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [8]:
# Step 1: Add a bonus array to salaries using broadcasting
bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus # Adds corresponding bonus to each column
print("Salaries after bonus:\n", salaries_with_bonus)

Salaries after bonus:
 [[ 55  70  85]
 [ 85 100 115]]


In [9]:
# Step 1: Mean of years of experience
print("Mean experience:", np.mean(years_exp))

# Step 2: Standard deviation of experience
print("Std deviation of experience:", np.std(years_exp))

# Step 3: Max and Min salaries
print("Max salary:", np.max(salaries), "Min salary:", np.min(salaries))

# Step 4: Sum of salaries
print("Sum of all salaries:", np.sum(salaries))

Mean experience: 5.2
Std deviation of experience: 3.1240998703626617
Max salary: 100 Min salary: 50
Sum of all salaries: 450


In [10]:
# Step 1: Apply trigonometric functions
angles = np.array([0, np.pi/4, np.pi/2])
print("Sine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))

# Step 2: Apply function along rows (sum salaries per person)
salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Sum of Salaries per person:", salary_sums)

Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [180 270]


In [13]:

%pip install pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 29.4 MB/s  0:00:00m0:00:010:01
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import pandas as pd

# Step 1: Create a NumPy array of random data
data = np.random.randint(1, 50, size=(5, 3))

# Step 2: Convert the array into a DataFrame
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print("Generated Data:\n", df_data)

# Step 3: Apply NumPy functions to DataFrame columns
df_data['Log_X'] = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])
print("DataFrame with NumPy Transformations:\n", df_data)

# Step 4: Analyze data using Pandas correlation
print("Correlation Matrix:\n", df_data.corr())

Generated Data:
     X   Y   Z
0  17   4   1
1  29  46   6
2   6   1  20
3  31  17  11
4   2  27  30
DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0  17   4   1  2.833213  2.000000
1  29  46   6  3.367296  6.782330
2   6   1  20  1.791759  1.000000
3  31  17  11  3.433987  4.123106
4   2  27  30  0.693147  5.196152
Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000  0.389213 -0.734135  0.952728  0.408139
Y       0.389213  1.000000  0.005902  0.172953  0.978299
Z      -0.734135  0.005902  1.000000 -0.877146  0.038305
Log_X   0.952728  0.172953 -0.877146  1.000000  0.160002
Sqrt_Y  0.408139  0.978299  0.038305  0.160002  1.000000


In [3]:
# Step 1: Save the DataFrame to a CSV file
df_data.to_csv('sample_data.csv', index=False)
print("Data saved to 'sample_data.csv'.")

# Step 2: Load the CSV file back into a new DataFrame
df_imported = pd.read_csv('sample_data.csv')
print("Imported DataFrame:\n", df_imported)

# Step 3: Generate summary statistics
summary_stats = df_imported.describe()
print("Summary Statistics:\n", summary_stats)

# Step 4: Display column means and standard deviations
print("Column Means:\n", df_imported.mean())
print("Column Standard Deviations:\n", df_imported.std())

Data saved to 'sample_data.csv'.
Imported DataFrame:
     X   Y   Z     Log_X    Sqrt_Y
0  17   4   1  2.833213  2.000000
1  29  46   6  3.367296  6.782330
2   6   1  20  1.791759  1.000000
3  31  17  11  3.433987  4.123106
4   2  27  30  0.693147  5.196152
Summary Statistics:
                X          Y          Z     Log_X    Sqrt_Y
count   5.000000   5.000000   5.000000  5.000000  5.000000
mean   17.000000  19.000000  13.600000  2.423881  3.820318
std    13.095801  18.343936  11.545562  1.169713  2.346586
min     2.000000   1.000000   1.000000  0.693147  1.000000
25%     6.000000   4.000000   6.000000  1.791759  2.000000
50%    17.000000  17.000000  11.000000  2.833213  4.123106
75%    29.000000  27.000000  20.000000  3.367296  5.196152
max    31.000000  46.000000  30.000000  3.433987  6.782330
Column Means:
 X         17.000000
Y         19.000000
Z         13.600000
Log_X      2.423881
Sqrt_Y     3.820318
dtype: float64
Column Standard Deviations:
 X         13.095801
Y         1

In [10]:
# Step 1: Load the Stack Overflow 2023 Developer Survey dataset
df_kaggle = pd.read_csv('survey_results_public.csv')
print("Loaded Dataset:\n", df_kaggle.head())

# Step 2: Select relevant columns (Updated to 2023 column names)
df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedCompYearly']]
print("Subset of Data:\n", df_subset.head())

# Step 3: Clean the data by dropping rows with missing values
df_clean = df_subset.dropna().copy()
print("Cleaned Data:\n", df_clean.head())

# Step 4: Categorize experience into groups
# Note: Converting YearsCodePro to numeric first to ensure the math works
df_clean['YearsCodePro'] = pd.to_numeric(df_clean['YearsCodePro'], errors='coerce')
df_clean = df_clean.dropna()
df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >= 10, 'Senior', 'Junior')

# Step 5: Group data by Country and ExperienceLevel, compute average salary
grouped_data = df_clean.groupby(['Country', 'ExperienceLevel'])['ConvertedCompYearly'].mean()
print("Grouped Average Salary:\n", grouped_data.head())

# Step 6: Reset index for readability
grouped_data = grouped_data.reset_index()
print("Formatted Grouped Data:\n", grouped_data.head())

Loaded Dataset:
    ResponseId     Q120                      MainBranch              Age  \
0           1  I agree                   None of these  18-24 years old   
1           2  I agree  I am a developer by profession  25-34 years old   
2           3  I agree  I am a developer by profession  45-54 years old   
3           4  I agree  I am a developer by profession  25-34 years old   
4           5  I agree  I am a developer by profession  25-34 years old   

                                          Employment  \
0                                                NaN   
1                                Employed, full-time   
2                                Employed, full-time   
3                                Employed, full-time   
4  Employed, full-time;Independent contractor, fr...   

                             RemoteWork  \
0                                   NaN   
1                                Remote   
2  Hybrid (some remote, some in-person)   
3  Hybrid (some remote,

In [13]:
import numpy as np
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478
np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)
mean_val = np.mean(data)
std_val = np.std(data)
print("Mean:", mean_val, "Std Dev:", std_val)

John Carl Misalang's Array: [ 98 111  44   6 126  83  93  71  84  84]
Mean: 80.0 Std Dev: 32.34810659064917


In [14]:
import numpy as np
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478
np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)
row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

John Carl Misalang's Matrix:
 [[34 47 44  6]
 [19 29  7 20]
 [20 16  7 37]]
Row sums: [131  75  80]
Column sums: [73 92 58 63]


In [15]:
import numpy as np
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478
np.random.seed(STUDENT_ID)
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)
slice_mid = arr3d[:,1,:]
print("Slice[:,1,:]:\n", slice_mid)

John Carl Misalang's 3D Array:
 [[[ 1 14 11]
  [ 5 18  6]
  [19 19 15]]

 [[ 6  4 26]
  [ 8 25 25]
  [ 0 14 18]]

 [[10  7 11]
  [10  6 27]
  [24 22 20]]]
Slice[:,1,:]:
 [[ 5 18  6]
 [ 8 25 25]
 [10  6 27]]


In [16]:
import numpy as np
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478
np.random.seed(STUDENT_ID)
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
filtered = x[(x>STUDENT_ID%50) & (x<STUDENT_ID%100)]
print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

John Carl Misalang's Original: [ 98 111  44   6 126  83  93  71  84  84]
Filtered subset: [44 71]


In [17]:
import numpy as np
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478
np.random.seed(STUDENT_ID)
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
print("Matrix A:\n", A)
print("Matrix B:\n", B)
product = A @ B
det_A = np.linalg.det(A)
print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[34 47]
 [44  6]]
Matrix B:
 [[19 29]
 [ 7 20]]
A @ B:
 [[ 975 1926]
 [ 878 1396]]
Determinant of A: -1863.9999999999998


In [18]:
import numpy as np
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478
angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)
print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

John Carl Misalang's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [19]:
import numpy as np
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478
np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))
arr[::2, ::2] = 0
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

John Carl Misalang's Modified 4x4 Array:
 [[ 0 47  0  6]
 [19 29  7 20]
 [ 0 16  0 37]
 [27  9  1 47]]


In [20]:
import numpy as np
STUDENT_NAME = "John Carl Misalaang"
STUDENT_ID = 20250478
np.random.seed(STUDENT_ID)
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)
grades = np.where(scores>=STUDENT_ID%70,'Pass','Fail')
print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

John Carl Misalaang's Scores: [ 97 110  43   5 125  82  92  70  83  83]
Grades: ['Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass']


In [21]:
import numpy as np
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
flat_arr = arr.flatten()
transposed_arr = arr.T
print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

Original array:
 [[34 47 44  6]
 [19 29  7 20]
 [20 16  7 37]]
Flattened: [34 47 44  6 19 29  7 20 20 16  7 37]
Transposed:
 [[34 19 20]
 [47 29 16]
 [44  7  7]
 [ 6 20 37]]


In [22]:
import numpy as np
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))
mask = arr % 2 == 0
arr[mask] = -1
print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[-1 47 -1]
 [-1 19 29]
 [ 7 -1 -1]]


In [23]:
import numpy as np
import pandas as pd
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name': [STUDENT_NAME]*5,
 'Score': np.random.randint(STUDENT_ID%50,
STUDENT_ID%100+50,5),
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})
print(df)

                 Name  Score  YearsCodePro
0  John Carl Misalang    125             6
1  John Carl Misalang     71            19
2  John Carl Misalang     33            19
3  John Carl Misalang    110            15
4  John Carl Misalang    120             6


In [24]:
import numpy as np
import pandas as pd
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'],
# Corrected to use a functional salary range, e.g., 40000 to 150000
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()
print(avg_salary)

EdLevel
Bachelor     74415.0
Master       79096.5
PhD         147141.0
Name: ConvertedComp, dtype: float64


In [25]:
import numpy as np
import pandas as pd
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
 'Country': ['Philippines','USA','UK','Canada','Germany'],
 'ConvertedComp': np.random.randint(40000, 150000, 5)
})

top5 = df.sort_values(by='ConvertedComp', ascending=False)
print(top5)

       Country  ConvertedComp
2           UK         147141
3       Canada         104765
4      Germany          82950
1          USA          75243
0  Philippines          44065


In [26]:
import numpy as np
import pandas as pd
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name':[STUDENT_NAME]*5,
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})
high_exp = df[df['YearsCodePro']>STUDENT_ID%10]
print(high_exp)

                 Name  YearsCodePro
1  John Carl Misalang            14
2  John Carl Misalang            11
4  John Carl Misalang            18


In [27]:
import numpy as np
import pandas as pd
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478

np.random.seed(STUDENT_ID)

df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})

bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']

df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)
print(df)

   ConvertedComp   Bracket
0          44065     0-50k
1          75243   50-100k
2         147141  100-150k
3         104765  100-150k
4          82950   50-100k


In [28]:
import numpy as np
import pandas as pd
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478

np.random.seed(STUDENT_ID)

# Original Code Issue:
# np.random.randint(STUDENT_ID%40000, STUDENT_ID%150000, 5)
# -> np.random.randint(12345, 12345, 5) which is a zero-length range.
# Corrected Code: Using a functional salary range (40000 to 150000)

df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})

df['LogComp'] = np.log(df['ConvertedComp'])
print(df)

   ConvertedComp    LogComp
0          44065  10.693421
1          75243  11.228478
2         147141  11.899147
3         104765  11.559475
4          82950  11.325993


In [29]:
import numpy as np
import pandas as pd
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5),
'ConvertedComp': np.random.randint(40000, 150000, 5)
})

corr_matrix = df.corr()
print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000      -0.232423
ConvertedComp     -0.232423       1.000000


In [32]:
import numpy as np
import pandas as pd
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'],
'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Calculate mean, median, and standard deviation for each 'EdLevel'
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean','median','std']).reset_index()
print(summary)

    EdLevel      mean    median           std
0  Bachelor   74415.0   74415.0  42921.381618
1    Master   79096.5   79096.5   5449.671963
2       PhD  147141.0  147141.0           NaN


In [33]:
import numpy as np
import pandas as pd
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478

np.random.seed(STUDENT_ID)

# Generate salaries: [100727, 136195, 130612, 100727, 95233]
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})

threshold = 110000

# Create the 'HighPay' column using np.where()
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')

print(df)

   ConvertedComp HighPay
0          44065      No
1          75243      No
2         147141     Yes
3         104765      No
4          82950      No


In [36]:
import numpy as np
import pandas as pd
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
'Country': ['Philippines','USA','UK','Canada','Germany'],
'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Group by 'Country' and calculate the mean and max 'ConvertedComp'
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean','max'])
print(top_countries)


                 mean     max
Country                      
Canada       104765.0  104765
Germany       82950.0   82950
Philippines   44065.0   44065
UK           147141.0  147141
USA           75243.0   75243


In [39]:
import numpy as np
import pandas as pd

# Basic Info
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478

# 1. Read the dataset
df = pd.read_csv('Most Popular Programming Languages.csv')

# --- FIX: Print columns to debug if 'Date' is missing ---
print("Detected Columns:", df.columns.tolist())

# Check if 'Date' exists; if not, look for 'Month' or 'date'
if 'Date' not in df.columns:
    if 'Month' in df.columns:
        df.rename(columns={'Month': 'Date'}, inplace=True)
    elif 'date' in df.columns:
        df.rename(columns={'date': 'Date'}, inplace=True)

# 2. Convert date column to datetime format
df['Date'] = pd.to_datetime(df['Date'])

# 3. Sort language columns alphabetically (excluding the 'Date' column)
languages = sorted([col for col in df.columns if col != 'Date'])

# 4. Assign language based on the last three digits of Student ID
language_index = (STUDENT_ID % 1000) % len(languages)
assigned_language = languages[language_index]

# 5. Extract data for the assigned language
lang_df = df[['Date', assigned_language]].copy()
lang_df.columns = ['Month', 'Popularity']

# 6. Compute Growth Rate (percentage)
lang_df['Growth_Rate'] = lang_df['Popularity'].pct_change() * 100

# 7. Calculate Rolling Statistics (12-month window)
lang_df['Moving_Avg'] = lang_df['Popularity'].rolling(window=12).mean()
lang_df['Moving_STD'] = lang_df['Popularity'].rolling(window=12).std()

# 8. Classify Growth Phases
growth_threshold = 5.0
decline_threshold = -5.0

lang_df['Phase'] = np.select(
    [
        lang_df['Growth_Rate'] > growth_threshold,
        lang_df['Growth_Rate'] < decline_threshold
    ],
    ['Growth', 'Decline'],
    default='Stable'
)

# 9. Key Performance Metrics
initial_val = lang_df['Popularity'].iloc[0]
final_val = lang_df['Popularity'].iloc[-1]
overall_growth = ((final_val - initial_val) / initial_val) * 100
phase_counts = lang_df['Phase'].value_counts()

# --- OUTPUTS ---
print(f"\nStudent Name: {STUDENT_NAME}")
print(f"Assigned Language: {assigned_language}")
print("-" * 30)
print("\nDataFrame Output (First 10 records):")
print(lang_df.head(10))
print("\nStatistical Summary Table:")
print(lang_df['Popularity'].describe())
print("\nGrowth Phase Counts:")
print(phase_counts)
print("\nKey Performance Metrics:")
print(f"Initial Popularity: {initial_val:.2f}")
print(f"Final Popularity: {final_val:.2f}")
print(f"Overall Growth Percentage: {overall_growth:.2f}%")

Detected Columns: ['Month', 'Python Worldwide(%)', 'JavaScript Worldwide(%)', 'Java Worldwide(%)', 'C# Worldwide(%)', 'PhP Worldwide(%)', 'Flutter Worldwide(%)', 'React Worldwide(%)', 'Swift Worldwide(%)', 'TypeScript Worldwide(%)', 'Matlab Worldwide(%)']

Student Name: John Carl Misalang
Assigned Language: Swift Worldwide(%)
------------------------------

DataFrame Output (First 10 records):
       Month  Popularity  Growth_Rate  Moving_Avg  Moving_STD    Phase
0 2004-01-01           9          NaN         NaN         NaN   Stable
1 2004-02-01           9     0.000000         NaN         NaN   Stable
2 2004-03-01           9     0.000000         NaN         NaN   Stable
3 2004-04-01           9     0.000000         NaN         NaN   Stable
4 2004-05-01          10    11.111111         NaN         NaN   Growth
5 2004-06-01           9   -10.000000         NaN         NaN  Decline
6 2004-07-01          10    11.111111         NaN         NaN   Growth
7 2004-08-01          27   170.0000

In [42]:
import numpy as np
import pandas as pd

# Basic Info
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478

# 1. Load the dataset
# Update filename if your actual file is named differently
df = pd.read_csv('Most Popular Programming Languages.csv')

# Handle column naming variations from Kaggle (convert Date to Month if needed)
if 'Date' in df.columns:
    df.rename(columns={'Date': 'Month'}, inplace=True)
elif 'date' in df.columns:
    df.rename(columns={'date': 'Month'}, inplace=True)

# Parse the Month column as datetime type
df['Month'] = pd.to_datetime(df['Month'])

# 2. Select assigned language for individual analysis
# Sort alphabetically (excluding the 'Month' column)
languages = sorted([col for col in df.columns if col != 'Month'])
language_index = (STUDENT_ID % 1000) % len(languages)
assigned_language = languages[language_index]

# Extract data
lang_df = df[['Month', assigned_language]].copy()
lang_df.columns = ['Month', 'Popularity']

# 3. Compute growth rate
lang_df['Growth_Rate'] = lang_df['Popularity'].pct_change() * 100

# 4. Smooth the trend
lang_df['Moving_Avg'] = lang_df['Popularity'].rolling(window=6).mean()
lang_df['Moving_STD'] = lang_df['Popularity'].rolling(window=6).std()

# 5. Analyze central tendency using NumPy
# Drop NaN values (like the first row) before calculating mean and std
clean_growth = lang_df['Growth_Rate'].dropna()
overall_mean = np.mean(clean_growth)
overall_std = np.std(clean_growth)

# 6. Apply lifecycle classification using np.select()
conditions = [
    np.abs(lang_df['Growth_Rate']) <= 1.0,                                      # Maturity: |Growth rate| <= 1%
    (lang_df['Growth_Rate'] < 0) & (lang_df['Growth_Rate'] < -overall_std),     # Decline: < 0 and below (-1 * std)
    lang_df['Growth_Rate'] > overall_mean,                                      # Growth: > mean
    (lang_df['Growth_Rate'] > 0) & (lang_df['Growth_Rate'] <= overall_mean)     # Introduction: > 0 but below mean
]

choices = ['Maturity', 'Decline', 'Growth', 'Introduction']

# Assign phases (Using 'Transition' for any edge-case months that fall between thresholds)
lang_df['Lifecycle_Phase'] = np.select(conditions, choices, default='Transition')

# Clean up the very first month which has no prior data to compare to
lang_df.loc[lang_df['Growth_Rate'].isna(), 'Lifecycle_Phase'] = 'Initial'

# 7. Summarize distribution
# Exclude the 'Initial' row for accurate calculations
valid_phases = lang_df[lang_df['Lifecycle_Phase'] != 'Initial']['Lifecycle_Phase']
phase_counts = valid_phases.value_counts()
phase_percentages = (phase_counts / len(valid_phases)) * 100

# Identify dominant stage
dominant_stage = phase_counts.idxmax()

# --- OUTPUTS ---
print(f"Student Name: {STUDENT_NAME}")
print(f"Assigned Language: {assigned_language}")
print("-" * 60)

print("\nLifecycle Classification Table (Last 10 Months):")
print(lang_df.tail(10))

print("-" * 60)
print("\nSummary Output:")
print("\nCount per Lifecycle Phase:")
print(phase_counts)
print("\nPercentage per Lifecycle Phase (%):")
print(phase_percentages.round(2))

print(f"\nDominant Stage:")
print(f"-> {assigned_language} is primarily categorized by the '{dominant_stage}' phase.")
if dominant_stage == 'Maturity':
    print(f"   Interpretation: {assigned_language} is currently in the maturity phase with stable global adoption.")
elif dominant_stage == 'Growth':
    print(f"   Interpretation: {assigned_language} is experiencing periods of significant, continuous adoption.")
elif dominant_stage == 'Decline':
    print(f"   Interpretation: {assigned_language} has faced consistent drops in popularity compared to its historical average.")
elif dominant_stage == 'Introduction':
    print(f"   Interpretation: {assigned_language} sees slow but steady positive adoption.")

print("-" * 60)
print("\nInterpretive Insights:")

# Check transitions over the last 12 months for resurgence/decline insights
recent_12_months = lang_df['Lifecycle_Phase'].tail(12).tolist()
# Reduce consecutive duplicates to show clear transitions
transitions = pd.Series(recent_12_months).loc[pd.Series(recent_12_months).shift() != pd.Series(recent_12_months)].tolist()

print(f"Transitions over the last year: {' -> '.join(transitions)}")

if 'Decline' in recent_12_months[-3:]:
    print("Trajectory: Indications of a recent decline in popularity.")
elif 'Growth' in recent_12_months[-3:]:
    print("Trajectory: Indications of a possible resurgence and strong recent growth.")
elif 'Maturity' in recent_12_months[-3:]:
    print("Trajectory: The language's adoption rate has flattened into stable maturity recently.")

Student Name: John Carl Misalang
Assigned Language: Swift Worldwide(%)
------------------------------------------------------------

Lifecycle Classification Table (Last 10 Months):
         Month  Popularity  Growth_Rate  Moving_Avg  Moving_STD  \
239 2023-12-01          66   -14.285714   71.000000    6.633250   
240 2024-01-01          65    -1.515152   70.166667    7.082843   
241 2024-02-01         100    53.846154   76.666667   12.675436   
242 2024-03-01          59   -41.000000   74.166667   14.634434   
243 2024-04-01          77    30.508475   74.000000   14.587666   
244 2024-05-01          61   -20.779221   71.333333   15.370968   
245 2024-06-01          61     0.000000   70.500000   15.846135   
246 2024-07-01          55    -9.836066   68.833333   17.022534   
247 2024-08-01          58     5.454545   61.833333    7.756718   
248 2024-09-01          59     1.724138   61.833333    7.756718   

    Lifecycle_Phase  
239      Transition  
240      Transition  
241          G

In [43]:
import numpy as np
import pandas as pd

# Basic Info
STUDENT_NAME = "John Carl Misalang"
STUDENT_ID = 20250478

# 1. Load dataset
# Update filename if your actual file is named differently
df = pd.read_csv('Most Popular Programming Languages.csv')

# Handle column naming variations from Kaggle
if 'Date' in df.columns:
    df.rename(columns={'Date': 'Month'}, inplace=True)
elif 'date' in df.columns:
    df.rename(columns={'date': 'Month'}, inplace=True)

# Parse the Month column as datetime type
df['Month'] = pd.to_datetime(df['Month'])

# 2. Select assigned languages
languages = sorted([col for col in df.columns if col != 'Month'])
lang1_index = (STUDENT_ID % 1000) % len(languages)
# Next language alphabetically (using modulo to wrap around if it's the last one)
lang2_index = (lang1_index + 1) % len(languages) 

lang1 = languages[lang1_index]
lang2 = languages[lang2_index]

comp_df = df[['Month', lang1, lang2]].copy()

# 3. Compute central tendencies
mean_1, median_1, std_1 = comp_df[lang1].mean(), comp_df[lang1].median(), comp_df[lang1].std()
mean_2, median_2, std_2 = comp_df[lang2].mean(), comp_df[lang2].median(), comp_df[lang2].std()

# 4. Normalize data using NumPy (Z-Score normalization to align scales)
comp_df[f'{lang1}_Norm'] = (comp_df[lang1] - mean_1) / std_1
comp_df[f'{lang2}_Norm'] = (comp_df[lang2] - mean_2) / std_2

# 5. Calculate correlation coefficient
correlation = np.corrcoef(comp_df[lang1], comp_df[lang2])[0, 1]

# 6. Determine dominance ratio
total_months = len(comp_df)
dom_1_count = np.sum(comp_df[lang1] > comp_df[lang2])
dom_2_count = np.sum(comp_df[lang2] > comp_df[lang1])

dom_ratio_1 = (dom_1_count / total_months) * 100
dom_ratio_2 = (dom_2_count / total_months) * 100

# 7. Compute Relative Performance Index (RPI) 
# RPI = Ratio of Means (Lang A vs Lang B)
rpi = mean_1 / mean_2 if mean_2 != 0 else np.nan

# 8. Identify cross-over points (months when the leader changes)
# Create a series of signs (1 if Lang1 > Lang2, -1 if Lang2 > Lang1, 0 if equal)
diff = comp_df[lang1] - comp_df[lang2]
signs = np.sign(diff)
# Find indices where the sign changes
sign_changes = np.where(np.diff(signs) != 0)[0] + 1 
crossovers = comp_df.iloc[sign_changes][['Month', lang1, lang2]]

# 9. Summarize comparative statistics in a DataFrame
stats_summary = pd.DataFrame({
    'Metric': ['Mean', 'Median', 'Std Dev', 'Dominance Ratio (%)'],
    lang1: [mean_1, median_1, std_1, dom_ratio_1],
    lang2: [mean_2, median_2, std_2, dom_ratio_2]
})

# --- OUTPUTS ---
print(f"Student Name: {STUDENT_NAME}")
print(f"Assigned Language 1: {lang1}")
print(f"Assigned Language 2: {lang2}")
print("-" * 60)

print("\nComparative Statistics Table:")
print(stats_summary.to_string(index=False))

print(f"\nCorrelation between {lang1} and {lang2}: {correlation:.4f}")
print(f"Relative Performance Index (RPI: {lang1}/{lang2}): {rpi:.4f}")

print("\nCross-Over Points (Months where the dominant language swapped):")
if crossovers.empty:
    print("No cross-over points found. One language dominated entirely.")
else:
    # Display the first few crossovers if there are many
    print(crossovers.head(10).to_string(index=False))
    if len(crossovers) > 10:
        print(f"... and {len(crossovers) - 10} more cross-over events.")

print("-" * 60)
print("\nInterpretation:")
# Determine the more consistent/resilient language based on Std Dev and Dominance
dominant = lang1 if dom_ratio_1 > dom_ratio_2 else lang2
consistent = lang1 if std_1 < std_2 else lang2

print(f"-> Dominance: {dominant} has been more historically dominant, leading for {max(dom_ratio_1, dom_ratio_2):.1f}% of the recorded months.")

if correlation > 0.7:
    print(f"-> Correlation: Strong positive correlation ({correlation:.2f}). Both languages tend to grow or decline together.")
elif correlation < -0.7:
    print(f"-> Correlation: Strong negative correlation ({correlation:.2f}). As one language grows, the other tends to decline.")
else:
    print(f"-> Correlation: Weak or moderate correlation ({correlation:.2f}). Their popularity trends are relatively independent.")

print(f"-> Consistency: {consistent} shows less variability (lower Standard Deviation), indicating more resilient, stable adoption over the 20-year span.")

Student Name: John Carl Misalang
Assigned Language 1: Swift Worldwide(%)
Assigned Language 2: TypeScript Worldwide(%)
------------------------------------------------------------

Comparative Statistics Table:
             Metric  Swift Worldwide(%)  TypeScript Worldwide(%)
               Mean           30.678715                23.405622
             Median           29.000000                 4.000000
            Std Dev           15.328697                28.603098
Dominance Ratio (%)           66.666667                33.333333

Correlation between Swift Worldwide(%) and TypeScript Worldwide(%): 0.4705
Relative Performance Index (RPI: Swift Worldwide(%)/TypeScript Worldwide(%)): 1.3107

Cross-Over Points (Months where the dominant language swapped):
     Month  Swift Worldwide(%)  TypeScript Worldwide(%)
2017-04-01                  26                       27
2017-08-01                  48                       30
2018-02-01                  29                       36
2024-02-01     